### ISSUE TITLE
Publicity question

### ISSUE THREAD

**Issue by AlexKhotian** [Unity-Technologies/OpenCppCoverage#1]
Hi!
I have a question about publicity of this project? As far as I understood, you had added Linux support for OpenCppCoverage tool. Do you plan to have this fork publicly available? If so maybe we can help with alpha/beta testing.
I made to build on Debian, but, unfortunately, have some problems with usage. May I ask you to guide me here?

**Comment by miniwolf** [comment]
There is not full support for coverage on linux. The tool behind is a windows only version that is using breakpoint injection to compute the coverage of the test executables, which is not a cross platform way to do it. For linux projects I would recommend looking into [dynamorio/drcov](https://github.com/DynamoRIO/dynamorio), which has much more crossplatform support than this tool.
What is working cross platform in this fork of the project is the reporting of the coverage report. In addition I added support for the output from DrCov so it could be merged into a solution.

**Comment by AlexKhotian** [comment]
@miniwolf Thx!
